/*
ACMI public API

A public API for ACMI's collection data including Films, TV Shows, Videogames and Art.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goacmi

import (
	"encoding/json"
)

// checks if the Get200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Get200Response{}

// Get200Response struct for Get200Response
type Get200Response struct {
	Message *string `json:"message,omitempty"`
	Api []string `json:"api,omitempty"`
	Acknowledgement *string `json:"acknowledgement,omitempty"`
}

// NewGet200Response instantiates a new Get200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGet200Response() *Get200Response {
	this := Get200Response{}
	return &this
}

// NewGet200ResponseWithDefaults instantiates a new Get200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGet200ResponseWithDefaults() *Get200Response {
	this := Get200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *Get200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Get200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *Get200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *Get200Response) SetMessage(v string) {
	o.Message = &v
}

// GetApi returns the Api field value if set, zero value otherwise.
func (o *Get200Response) GetApi() []string {
	if o == nil || IsNil(o.Api) {
		var ret []string
		return ret
	}
	return o.Api
}

// GetApiOk returns a tuple with the Api field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Get200Response) GetApiOk() ([]string, bool) {
	if o == nil || IsNil(o.Api) {
		return nil, false
	}
	return o.Api, true
}

// HasApi returns a boolean if a field has been set.
func (o *Get200Response) HasApi() bool {
	if o != nil && !IsNil(o.Api) {
		return true
	}

	return false
}

// SetApi gets a reference to the given []string and assigns it to the Api field.
func (o *Get200Response) SetApi(v []string) {
	o.Api = v
}

// GetAcknowledgement returns the Acknowledgement field value if set, zero value otherwise.
func (o *Get200Response) GetAcknowledgement() string {
	if o == nil || IsNil(o.Acknowledgement) {
		var ret string
		return ret
	}
	return *o.Acknowledgement
}

// GetAcknowledgementOk returns a tuple with the Acknowledgement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Get200Response) GetAcknowledgementOk() (*string, bool) {
	if o == nil || IsNil(o.Acknowledgement) {
		return nil, false
	}
	return o.Acknowledgement, true
}

// HasAcknowledgement returns a boolean if a field has been set.
func (o *Get200Response) HasAcknowledgement() bool {
	if o != nil && !IsNil(o.Acknowledgement) {
		return true
	}

	return false
}

// SetAcknowledgement gets a reference to the given string and assigns it to the Acknowledgement field.
func (o *Get200Response) SetAcknowledgement(v string) {
	o.Acknowledgement = &v
}

func (o Get200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Get200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Api) {
		toSerialize["api"] = o.Api
	}
	if !IsNil(o.Acknowledgement) {
		toSerialize["acknowledgement"] = o.Acknowledgement
	}
	return toSerialize, nil
}

type NullableGet200Response struct {
	value *Get200Response
	isSet bool
}

func (v NullableGet200Response) Get() *Get200Response {
	return v.value
}

func (v *NullableGet200Response) Set(val *Get200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGet200Response(val *Get200Response) *NullableGet200Response {
	return &NullableGet200Response{value: val, isSet: true}
}

func (v NullableGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


