/*
ACMI public API

A public API for ACMI's collection data including Films, TV Shows, Videogames and Art.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goacmi

import (
	"encoding/json"
)

// checks if the WorkRecommendationsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkRecommendationsInner{}

// WorkRecommendationsInner struct for WorkRecommendationsInner
type WorkRecommendationsInner struct {
	DisplayName *string `json:"display_name,omitempty"`
	JobTitle *string `json:"job_title,omitempty"`
	AvatarImage *string `json:"avatar_image,omitempty"`
	Quote *string `json:"quote,omitempty"`
}

// NewWorkRecommendationsInner instantiates a new WorkRecommendationsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkRecommendationsInner() *WorkRecommendationsInner {
	this := WorkRecommendationsInner{}
	return &this
}

// NewWorkRecommendationsInnerWithDefaults instantiates a new WorkRecommendationsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkRecommendationsInnerWithDefaults() *WorkRecommendationsInner {
	this := WorkRecommendationsInner{}
	return &this
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *WorkRecommendationsInner) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkRecommendationsInner) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *WorkRecommendationsInner) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *WorkRecommendationsInner) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetJobTitle returns the JobTitle field value if set, zero value otherwise.
func (o *WorkRecommendationsInner) GetJobTitle() string {
	if o == nil || IsNil(o.JobTitle) {
		var ret string
		return ret
	}
	return *o.JobTitle
}

// GetJobTitleOk returns a tuple with the JobTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkRecommendationsInner) GetJobTitleOk() (*string, bool) {
	if o == nil || IsNil(o.JobTitle) {
		return nil, false
	}
	return o.JobTitle, true
}

// HasJobTitle returns a boolean if a field has been set.
func (o *WorkRecommendationsInner) HasJobTitle() bool {
	if o != nil && !IsNil(o.JobTitle) {
		return true
	}

	return false
}

// SetJobTitle gets a reference to the given string and assigns it to the JobTitle field.
func (o *WorkRecommendationsInner) SetJobTitle(v string) {
	o.JobTitle = &v
}

// GetAvatarImage returns the AvatarImage field value if set, zero value otherwise.
func (o *WorkRecommendationsInner) GetAvatarImage() string {
	if o == nil || IsNil(o.AvatarImage) {
		var ret string
		return ret
	}
	return *o.AvatarImage
}

// GetAvatarImageOk returns a tuple with the AvatarImage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkRecommendationsInner) GetAvatarImageOk() (*string, bool) {
	if o == nil || IsNil(o.AvatarImage) {
		return nil, false
	}
	return o.AvatarImage, true
}

// HasAvatarImage returns a boolean if a field has been set.
func (o *WorkRecommendationsInner) HasAvatarImage() bool {
	if o != nil && !IsNil(o.AvatarImage) {
		return true
	}

	return false
}

// SetAvatarImage gets a reference to the given string and assigns it to the AvatarImage field.
func (o *WorkRecommendationsInner) SetAvatarImage(v string) {
	o.AvatarImage = &v
}

// GetQuote returns the Quote field value if set, zero value otherwise.
func (o *WorkRecommendationsInner) GetQuote() string {
	if o == nil || IsNil(o.Quote) {
		var ret string
		return ret
	}
	return *o.Quote
}

// GetQuoteOk returns a tuple with the Quote field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkRecommendationsInner) GetQuoteOk() (*string, bool) {
	if o == nil || IsNil(o.Quote) {
		return nil, false
	}
	return o.Quote, true
}

// HasQuote returns a boolean if a field has been set.
func (o *WorkRecommendationsInner) HasQuote() bool {
	if o != nil && !IsNil(o.Quote) {
		return true
	}

	return false
}

// SetQuote gets a reference to the given string and assigns it to the Quote field.
func (o *WorkRecommendationsInner) SetQuote(v string) {
	o.Quote = &v
}

func (o WorkRecommendationsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkRecommendationsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DisplayName) {
		toSerialize["display_name"] = o.DisplayName
	}
	if !IsNil(o.JobTitle) {
		toSerialize["job_title"] = o.JobTitle
	}
	if !IsNil(o.AvatarImage) {
		toSerialize["avatar_image"] = o.AvatarImage
	}
	if !IsNil(o.Quote) {
		toSerialize["quote"] = o.Quote
	}
	return toSerialize, nil
}

type NullableWorkRecommendationsInner struct {
	value *WorkRecommendationsInner
	isSet bool
}

func (v NullableWorkRecommendationsInner) Get() *WorkRecommendationsInner {
	return v.value
}

func (v *NullableWorkRecommendationsInner) Set(val *WorkRecommendationsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkRecommendationsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkRecommendationsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkRecommendationsInner(val *WorkRecommendationsInner) *NullableWorkRecommendationsInner {
	return &NullableWorkRecommendationsInner{value: val, isSet: true}
}

func (v NullableWorkRecommendationsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkRecommendationsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


